services:
  - type: web
    name: data-mesh-maturity
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_deploy:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
